### PR TITLE
add logout button in secured/home.xhtml

### PR DESCRIPTION
**Pull request by subaochen**
add logout button in secured/home.xhtml page and logout action in
AuthenticationListener.java
move @Secured annotation of Pages.java to folder,in order to protected
the whole folder

### CODE REVIEW

**Comment by johnament** [comment]
Hi Su!

First, thanks for the PR.  Please create a JIRA describing your change - looks like you're updating our examples to include a logout link.  Once you've done that, please amend your commit with the JIRA ticket #.

In addition, it looks like you have a checkstyle violation in your code.

**Comment by subaochen** [comment]
I have created issue at: https://issues.apache.org/jira/browse/DELTASPIKE-1201, but I can not get the detail of  the code checkstyle viloation, would you like to show some hints? I'm sorry, I know little about Jenkins, and can not get enough information from Jenkins. 

Thanks a lot!

**Comment by johnament** [comment]
This is what the output says 
```
[INFO] --- maven-checkstyle-plugin:2.9.1:check (verify-style) @ deltaspike-security-requested-page-after-login-picketlink ---
[INFO] Starting audit...
/home/jenkins/jenkins-slave/workspace/DeltaSpike-PR-Builder/deltaspike/examples/security-requested-page-after-login-picketlink/src/main/java/org/apache/deltaspike/example/security/requestedpage/picketlink/AuthenticationListener.java:48:66: '{' should be on a new line.
Audit done.

[INFO] There are 1 checkstyle errors.
[INFO] -----------------------------------
```

You should compile the module locally as well.

**Comment by subaochen** [comment]
hi johnament,

I have fixed the checkstyle violation. I often run mvn clean package but not mvn clean install , so check-style-plugin not working, will follow you guide next time, thanks again!

**Comment by johnament** [comment]
Hi @subaochen you're correct, build looks good now.  However, still need the commits to include the JIRA ticket in them and if you can squash them together that would be great.

**Comment by subaochen** [comment]
hi @johnament , I have looked around git log of deltaspike to learn how to write the comment followed the deltaspike way. I'd like to close this PR and create a new PR again, ok?

**Comment by johnament** [comment]
If you want you can, however you can also just `git push -f` after making your fixes locally.  This [page](http://deltaspike.apache.org/suggested-git-workflows.html#RaisingPullRequests) may give you more info as well.

**Pull request closed without merging**
