### PR TITLE
Make it possible to test against latest WildFly.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by rafabene** [comment]
Hi @tremes . Is there a Jira ticket associated with it ?

**Comment by tremes** [comment]
No it isn't. Should I create one?

**Comment by rafabene** [comment]
It should be good to have a Jira ticket so we can track the motivation of the changes and also to be part of the release notes.

I also appreciate if you can include the Ticket reference in your commit message.

Thanks a lot for your contributions

P.S: It's funny because I've already made this modification before: https://github.com/apache/deltaspike/commit/afa43333526f204d373c9cdd4118e73bdf6750fc

**Comment by rafabene** [comment]
I also tried your PR and it fails with `mvn clean install -Pwildfly-build-managed`

**Comment by tremes** [comment]
I am closing this one and will reopen new one with issue number. Which WF version are you trying? I can't see any failures.

**Pull request closed without merging**
