### PR TITLE
DELTASPIKE-1330 fix

### PR DESCRIPTION
**Pull request by arthurgregorio**
just updated line 47 to the correct method call

### CODE REVIEW

**Comment by tandraschko** [comment]
Hi,

first of all, thanks for the PR!
It would be great if you can provide 1-2 unittests for it.

**Comment by arthurgregorio** [comment]
uhmm, where i can make this testst? CriteriaTest class?

**Comment by tandraschko** [comment]
I don't have time to check it but i think we have similar tests. Just look for a good place :)

**Comment by arthurgregorio** [comment]
Ok, thx!

**Comment by arthurgregorio** [comment]
I will close this pull because i find the problem is not the deltaspike implementation, is in the way that we created the criterias... 

Sorry for unnecessary PR...

**Pull request closed without merging**
