### PR TITLE
MyFacesTest provides FacesContext for Jupiter test cases

### PR DESCRIPTION
**Pull request by shadogray**
FacesContext is provided by MyFaces Test in Jupiter test cases.

### CODE REVIEW

**Comment by shadogray** [comment]
apache-deltaspike.properties files have bee removed, so resource is null

**Comment by tandraschko** [comment]
it still doesnt fix the interdyn test?

**Comment by shadogray** [comment]
seems, that arquillian-container needs to be changed too, and
geronimo-jta-spec, and...
so major changes in POMs needed.

How ist it planned to continue on older versions (Weld3)?
Is it OK to dispense with all "javax.enterprise" ???

**Comment by tandraschko** [comment]
I dont understand your Question
DS2 is Jakarta only

**Comment by shadogray** [comment]
thank you for the clarification

Am Mo., 9. Okt. 2023 um 18:17 Uhr schrieb Thomas Andraschko <
***@***.***>:

**Comment by shadogray** [comment]
Help needed!
currently I have moved Weld profile to working dependencies and added
bean-discovery-mode to "all" on all arquillian tests.

But now I reach a full stop on the MessageContextTest:
MessageBundleExtension#install.. has been modified, which seems to be
incompatible with Weld, see stack trace below. I have no idea what to do
here.

Shall I check in what I have done until here?

[ERROR]   MessageContextTest Definition Exception List with 1 exceptions:
Exception 0 :
org.jboss.weld.exceptions.IllegalArgumentException: WELD-001508: Cannot
create an InjectionTarget from [EnhancedAnnotatedTypeImpl] public abstract
interface @MessageBundle @MessageContextConfig class
org.apache.deltaspike.test.core.api.message.MinimalMessages as it is an
interface
        at
org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:83)
        at
org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:70)
        at
org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl.read(BeanConfiguratorImpl.java:177)
        at
org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl.read(BeanConfiguratorImpl.java:63)
        at
org.apache.deltaspike.core.impl.message.MessageBundleExtension.installMessageBundleProducerBeans(MessageBundleExtension.java:150)
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown
Source)
        at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Am Mo., 9. Okt. 2023 um 17:58 Uhr schrieb Thomas Frühbeck <
***@***.***>:

**Comment by tandraschko** [comment]
@struberg can you assist?

**Pull request merged**
