### PR TITLE
DELTASPIKE-1434 - Further refining relocation patterns

### PR DESCRIPTION
**Pull request by rzo1**
Adds additional patterns for

- javax.el
- javax.faces
- javax.servlet
- javax.decorator

Example in TomEE looks basically good now... should be mostly complete now, I guess...

FYI @struberg

### CODE REVIEW

**Comment by rzo1** [comment]
ping @struberg

**Comment by struberg** [comment]
txs, patch applied!

**Comment by jin-harmoney** [comment]
@struberg, sorry to disturb you. Would it be possible to release the latest `master`. I'm currently on `1.9.6`, but I'm seeing issues with `javax.naming`. I think they will be resolved with the recent changes that have been done, but those are not yet released afaik. Thanks!

**Comment by rzo1** [comment]
@jin-harmoney Guess it would be better to drop a mail on the dev@ list.

**Pull request closed without merging**
